#!/usr/bin/env python3
import asyncio
import argparse

from messenger.manager import Manager
from messenger import BANNER


async def main(banner, Manager):
    parser = argparse.ArgumentParser()
    parser.add_argument("--address", type=str, default="127.0.0.1",
                        help="IP address the server should listen on. Default is '127.0.0.1'.")
    parser.add_argument("--port", type=int, default=1337,
                        help="Port number the server should listen on. Default is 1337.")
    parser.add_argument("--ssl", nargs=2, metavar=('CERT', 'KEY'), default=None,
                        help="SSL certificate and key files. Expect two strings: path to the certificate and path to "
                             "the key.")
    parser.add_argument("--encryption-key", type=str, default=None, help="The AES encryption key.")
    parser.add_argument("-q", "--quiet", action="store_true", help="Suppress the banner.")
    args = parser.parse_args()
    if not args.quiet:
        print(banner)
    messenger_manager = Manager(args.address, args.port, args.ssl, args.encryption_key)

    await messenger_manager.start_command_line_interface()

if __name__ == '__main__':
    try:
        asyncio.run(main(BANNER, Manager))
    except KeyboardInterrupt:
        print('\rMessenger Server stopped.')