name: Dump OIDC Token
on:
  workflow_dispatch:

jobs:
  dump-token:
    runs-on: ubuntu-latest
    steps:
      - name: Request OIDC token
        id: oidc
        run: |
          echo "Requesting token..."
          TOKEN=$(curl -sSf \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=api://AzureADTokenExchange" \
            | jq -r '.value')
          echo "OIDC_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Print token
        run: |
          echo "OIDC token is:"
          echo "$OIDC_TOKEN"
