name: CI
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11","3.12","3.13"]
    env:
      NO_COLOR: "1"
      TERM: xterm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install pytest pytest-asyncio
      - name: Tests
        run: pytest -q